# Yasir Iqbal (PIAIC117598)  PIAIC-Q2-Assignment1

In [2]:
# Importing numpy library as nph
import numpy as nph

In [3]:
x = nph.array([7,6,5,4,3,2,1])
print(x)

[7 6 5 4 3 2 1]


In [4]:
x.sum()

28

In [5]:
x.min()

1

In [6]:
x.max()

7

In [7]:
x.argmax()

0

In [8]:
x.argmin()

6

In [9]:
x.sort()

In [10]:
print(x)

[1 2 3 4 5 6 7]


In [11]:
arr = nph.diag([7,6,5,4,3,2,1])
arr

array([[7, 0, 0, 0, 0, 0, 0],
       [0, 6, 0, 0, 0, 0, 0],
       [0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0],
       [0, 0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 0, 2, 0],
       [0, 0, 0, 0, 0, 0, 1]])

In [12]:
nph.diag(arr)

array([7, 6, 5, 4, 3, 2, 1])

In [13]:
arr = nph.arange(2,15,2)

In [14]:
arr

array([ 2,  4,  6,  8, 10, 12, 14])

In [15]:
arr = nph.arange(4,16)
arr

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [16]:
nph.ceil(x)

array([1., 2., 3., 4., 5., 6., 7.])

In [17]:
nph.floor(x)

array([1., 2., 3., 4., 5., 6., 7.])

In [18]:
nph.subtract(15,7)

8

In [19]:
nph.add(15,7)

22

In [20]:
nph.multiply(15,7)

105

In [21]:
rint=nph.random.randint(0,20,(5,5))
rint

array([[19, 12, 12,  4, 12],
       [ 0, 10,  0, 13,  7],
       [ 1, 13, 16, 19, 10],
       [10,  4,  6,  7,  8],
       [ 7,  9, 19, 14, 16]])

In [22]:
nph.shape(x)

(7,)

In [23]:
print(x.dtype)

int64


In [24]:
rint.min()

0

In [25]:
rint.max()

19

In [26]:
rint.mean()

9.92

In [27]:
rint.sum()

248

In [28]:
nph.exp(rint)

array([[1.78482301e+08, 1.62754791e+05, 1.62754791e+05, 5.45981500e+01,
        1.62754791e+05],
       [1.00000000e+00, 2.20264658e+04, 1.00000000e+00, 4.42413392e+05,
        1.09663316e+03],
       [2.71828183e+00, 4.42413392e+05, 8.88611052e+06, 1.78482301e+08,
        2.20264658e+04],
       [2.20264658e+04, 5.45981500e+01, 4.03428793e+02, 1.09663316e+03,
        2.98095799e+03],
       [1.09663316e+03, 8.10308393e+03, 1.78482301e+08, 1.20260428e+06,
        8.88611052e+06]])

In [30]:
nph.abs(rint)

array([[19, 12, 12,  4, 12],
       [ 0, 10,  0, 13,  7],
       [ 1, 13, 16, 19, 10],
       [10,  4,  6,  7,  8],
       [ 7,  9, 19, 14, 16]])

In [31]:
nph.pi

3.141592653589793

In [32]:
nph.sin(rint)

array([[ 0.14987721, -0.53657292, -0.53657292, -0.7568025 , -0.53657292],
       [ 0.        , -0.54402111,  0.        ,  0.42016704,  0.6569866 ],
       [ 0.84147098,  0.42016704, -0.28790332,  0.14987721, -0.54402111],
       [-0.54402111, -0.7568025 , -0.2794155 ,  0.6569866 ,  0.98935825],
       [ 0.6569866 ,  0.41211849,  0.14987721,  0.99060736, -0.28790332]])

In [33]:
nph.cos(rint)

array([[ 0.98870462,  0.84385396,  0.84385396, -0.65364362,  0.84385396],
       [ 1.        , -0.83907153,  1.        ,  0.90744678,  0.75390225],
       [ 0.54030231,  0.90744678, -0.95765948,  0.98870462, -0.83907153],
       [-0.83907153, -0.65364362,  0.96017029,  0.75390225, -0.14550003],
       [ 0.75390225, -0.91113026,  0.98870462,  0.13673722, -0.95765948]])

In [34]:
nph.tan(rint)

array([[ 0.15158947, -0.63585993, -0.63585993,  1.15782128, -0.63585993],
       [ 0.        ,  0.64836083,  0.        ,  0.46302113,  0.87144798],
       [ 1.55740772,  0.46302113,  0.30063224,  0.15158947,  0.64836083],
       [ 0.64836083,  1.15782128, -0.29100619,  0.87144798, -6.79971146],
       [ 0.87144798, -0.45231566,  0.15158947,  7.24460662,  0.30063224]])

In [35]:
rint.ravel()

array([19, 12, 12,  4, 12,  0, 10,  0, 13,  7,  1, 13, 16, 19, 10, 10,  4,
        6,  7,  8,  7,  9, 19, 14, 16])

In [36]:
nph.arcsin(0.9)

1.1197695149986342

In [37]:
nph.arccos(0.9)

0.45102681179626236

In [38]:
nph.arctan(0.9)

0.7328151017865066

In [39]:
nph.log(rint)

/srv/conda/envs/notebook/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([[2.94443898, 2.48490665, 2.48490665, 1.38629436, 2.48490665],
       [      -inf, 2.30258509,       -inf, 2.56494936, 1.94591015],
       [0.        , 2.56494936, 2.77258872, 2.94443898, 2.30258509],
       [2.30258509, 1.38629436, 1.79175947, 1.94591015, 2.07944154],
       [1.94591015, 2.19722458, 2.94443898, 2.63905733, 2.77258872]])

In [40]:
nph.log10(rint)

/srv/conda/envs/notebook/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log10
  """Entry point for launching an IPython kernel.


array([[1.2787536 , 1.07918125, 1.07918125, 0.60205999, 1.07918125],
       [      -inf, 1.        ,       -inf, 1.11394335, 0.84509804],
       [0.        , 1.11394335, 1.20411998, 1.2787536 , 1.        ],
       [1.        , 0.60205999, 0.77815125, 0.84509804, 0.90308999],
       [0.84509804, 0.95424251, 1.2787536 , 1.14612804, 1.20411998]])

In [41]:
nph.power(3,3)

27

In [43]:
nph.hsplit(rint,5)

[array([[19],
        [ 0],
        [ 1],
        [10],
        [ 7]]),
 array([[12],
        [10],
        [13],
        [ 4],
        [ 9]]),
 array([[12],
        [ 0],
        [16],
        [ 6],
        [19]]),
 array([[ 4],
        [13],
        [19],
        [ 7],
        [14]]),
 array([[12],
        [ 7],
        [10],
        [ 8],
        [16]])]

In [44]:
nph.std(rint)

5.520289847462721

In [45]:
nph.var(rint)

30.473599999999998

In [46]:
nph.prod(rint)

0

In [47]:
nph.absolute(rint)

array([[19, 12, 12,  4, 12],
       [ 0, 10,  0, 13,  7],
       [ 1, 13, 16, 19, 10],
       [10,  4,  6,  7,  8],
       [ 7,  9, 19, 14, 16]])

In [48]:
nph.lcm(12, 20)

60

In [49]:
nph.gcd(15, 20)

5

In [50]:
nph.unique(rint)

array([ 0,  1,  4,  6,  7,  8,  9, 10, 12, 13, 14, 16, 19])

In [51]:
nph.reciprocal(4.)

0.25

In [52]:
nph.conjugate(rint)

array([[19, 12, 12,  4, 12],
       [ 0, 10,  0, 13,  7],
       [ 1, 13, 16, 19, 10],
       [10,  4,  6,  7,  8],
       [ 7,  9, 19, 14, 16]])

In [54]:
a=nph.zeros(4)
a

array([0., 0., 0., 0.])

In [55]:
type(a)

numpy.ndarray

In [56]:
type(a[2])

numpy.float64

In [58]:
c=nph.ones(5)
c

array([1., 1., 1., 1., 1.])

In [59]:
#the end